### ISSUE TITLE
Segmentation fault when dealing with files: Compiled AudMonkey 1.0.1 or latest Git: Debian Linux - Bookworm

### ISSUE THREAD

**Issue by Dizzy611** [AudMonkey/AudMonkey#103]
When attempting to use AudMonkey, either 1.0.1 or latest Git, compiled using the BUILDING.md instructions, I get a segfault whenever choosing to discard or recover projects, or when trying to save a project. The segfaults seem to be somehow related to a PNG file having a buffer issue in it? I'm not sure how to read these backtraces tbh.

Attached is the full bt for a "save project", down to when I no longer had debug symbols because they were left out of audmonkey's builtin libs, as well as the full bt for a "discard project", until the same.

[full_bt_saveproject.log](https://github.com/AudMonkey/AudMonkey/files/7536997/full_bt.log)
[bt_full_discard.log](https://github.com/AudMonkey/AudMonkey/files/7537026/bt_full_discard.log)

**Comment by IshoAntar** [comment]
I can't reproduce, but it seems to be something related to GTK?

Looking at the 'saveproject' backtrace, the following lines seem interesting:
```
#21 0x00007ffff76416e7 in wxArtProvider::GetIcon(wxString const&, wxString const&, wxSize const&) () at /usr/local/bin/../lib/audmonkey/libwx_gtk2u_core-3.1.so
#22 0x00005555562f9591 in WarningDialog::WarningDialog(wxWindow*, TranslatableString const&, TranslatableString const&, bool) ()
#23 0x00005555562f9a68 in ShowWarningDialog(wxWindow*, wxString const&, TranslatableString const&, bool, TranslatableString const&) ()
#24 0x0000555555c9a2fb in ProjectFileManager::SaveAs(bool) ()
```
At the bottom (`#24`) is call to the following function:
https://github.com/AudMonkey/AudMonkey/blob/e92b0b85986d51e40fcccb41fec61bd261fc52e6/src/ProjectFileManager.cpp#L417

Which in turn calls `ShowWarningDialog`:
https://github.com/AudMonkey/AudMonkey/blob/e92b0b85986d51e40fcccb41fec61bd261fc52e6/src/ProjectFileManager.cpp#L445
from here: https://github.com/AudMonkey/AudMonkey/blob/e92b0b85986d51e40fcccb41fec61bd261fc52e6/src/widgets/Warning.cpp#L92
Which then constructs a `WarningDialog` object, calling `GetIcon` in the process:
https://github.com/AudMonkey/AudMonkey/blob/e92b0b85986d51e40fcccb41fec61bd261fc52e6/src/widgets/Warning.cpp#L68

The rest of the calls (up the stack) are internal to wxWidgets that seem to create the icon using functionality provided by the backend (GTK in this case).

Though the icon seems to be a standard wxWidgets icon?

I'll have to take a closer look into this, as i'm not sure what the root cause might be.

**Comment by Dizzy611** [comment]
For reference I am using Cinnamon as my desktop environment, which uses GTK+3 underlying
